# 线上配置文件
# @author <a href="https://gitee.com/ouyang-jianli">程序员红逗</a>
# @from <a href="https://gitee.com/ouyang-jianli">程序员红逗的gitee</a>
server:
  port: 8101
  servlet:
    #    context-path: /api
    session:
      cookie:
        # cookie 30 天过期
        max-age: 2592000
        # 解决跨域
        same-site: none
        secure: true
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.77.222.74:3306/yangdadaprod
    username: root
    password: 20182018Aa#
  # Redis 配置
  redis:
    database: 1
    host: 120.77.222.74
    port: 6379
    timeout: 5000
    password: 20182018Aa
  #分库分表配置
  shardingsphere:
    #数据源配置
    datasource:
      # 多数据源以逗号隔开即可
      names: yangdada
      yangdada:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://120.77.222.74:3306/yangdadaprod
        username: root
        password: 20182018Aa#
    # 规则配置
    rules:
      sharding:
        # 分片算法配置
        sharding-algorithms:
          # 自定义分片规则名
          answer-table-inline:
            ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
            type: INLINE
            props:
              algorithm-expression: user_answer_$->{appId % 2}
        tables:
          user_answer:
            actual-data-nodes: yangdada.user_answer_$->{0..1}
            # 分表策略
            table-strategy:
              standard:
                sharding-column: appId
                sharding-algorithm-name: answer-table-inline
## 对象存储
#cos:
#  client:
#    accessKey: LTAI5tFQxVgjdu95mfneHkn5
#    secretKey: MoXpicgkhzn8nqaKYczsdBmzWqastg
#    region: oss-cn-shenzhen
#    bucket: yangdada-bucket
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
#AI配置
ai:
  apiKey: b1d2c6e522f8e82474aa7739cec61c12.EFSBjl5Mie2rhGA3
