# 测试配置文件
# @author <a href="https://github.com/ouyangtn">程序员红逗</a>
# @from <a href="https://github.com/ouyangtn">程序员红豆的github</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yangdadaprod
    username: root
    password: 20182018Aa
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 120.77.222.74
    port: 6379
    timeout: 5000
    password: 20182018Aa
